### ISSUE TITLE
Customize button

### ISSUE THREAD

**Issue by RitikDeqode** [thisisamir98/telegram-login-button#6]
Hi,

Can we customize the button? i.e. I don't want the text `Login with telegram` inside the button and also wanted to apply a custom style to the button.

Please suggest.
Thanks

**Comment by 1aerostorm** [comment]
Probably no... It is not by component, it is by Telegram. It loading in iframe so no CSS can be applied.
All customization options are https://core.telegram.org/widgets/login

**Comment by thisisamir98** [comment]
#9
