### ISSUE TITLE
<TelegramLoginButton /> should support style and another props forwarding

### ISSUE THREAD

**Issue by 1aerostorm** [thisisamir98/telegram-login-button#9]
(It will NOT customize button itself, because it is provided by Telegram and wrapped in iframe. But it can be usable for margins and another customization of `div` which wraps the button.)

**Comment by thisisamir98** [comment]
thanks for the suggestion, I added this in https://github.com/thisisamir98/telegram-login-button/commit/61e34e650f3b3e13a1cd6c65baab4a164b75198b
will soon publish it on npm.

**Comment by thisisamir98** [comment]
its wrapperProps now. you can pass anything to the wrapper div with it.
